services:  
  frontend:  
    build: ./frontend  
    ports: ["8081:8080"]  
    volumes:  
      - ./frontend:/app
      - /app/node_modules  # Prevent host node_modules override  
    environment:
      - NODE_ENV=development
    stdin_open: true  
    tty: true  
    networks:  
      - app-network  

  backend:  
    build: ./backend  
    ports: ["8000:8000"]  
    volumes:  
      - ./backend:/app  
    depends_on:  
      - db  
    networks:  
      - app-network  

  db:  
    image: postgres:14  
    environment:  
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: password123  
      POSTGRES_DB: language_app  
    ports: ["5432:5432"]  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  
    networks:  
      - app-network  

volumes:  
  postgres_data:  

networks:  
  app-network:  
    driver: bridge  